language: csharp
os: linux
mono: none
sudo: required
dotnet: 3.1

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
        key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - dpkg
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8

git:
  depth: false

jobs:
  include:
    - stage: debug_compile
      script: ./build.sh compile --configuration Debug
    - stage: debug_test
      script: ./build.sh test --configuration Debug
    - stage: compile
      script: ./build.sh compile --configuration Release
    - stage: test
      script: ./build.sh test --configuration Release

stages:
  - name: debug_compile
    if: branch != master
  - name: debug_test
    if: branch != master
  - name: compile
    if: branch = master
  - name: test
    if: branch = master
