// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Octogram.Chats.Infrastructure.Repository.EntityFrameworkCore;

namespace Octogram.Chats.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20200528130751_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Messenger.Domain.Chats.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnName("CreateDate")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("OwnedId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnedId")
                        .IsUnique();

                    b.ToTable("Chats");

                    b.HasDiscriminator<string>("Type").HasValue("Chat");
                });

            modelBuilder.Entity("Messenger.Domain.Interlocutors.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Messenger.Domain.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnName("Content")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTimeOffset>("SentDate")
                        .HasColumnName("SentDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("State")
                        .HasColumnType("text")
                        .HasDefaultValue("Sending");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Messenger.Domain.Chats.DirectChat", b =>
                {
                    b.HasBaseType("Messenger.Domain.Chats.Chat");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("DirectChat");
                });

            modelBuilder.Entity("Messenger.Domain.Chats.Chat", b =>
                {
                    b.HasOne("Messenger.Domain.Interlocutors.Member", "Owned")
                        .WithOne()
                        .HasForeignKey("Messenger.Domain.Chats.Chat", "OwnedId");
                });

            modelBuilder.Entity("Messenger.Domain.Messages.Message", b =>
                {
                    b.HasOne("Messenger.Domain.Chats.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId");
                });

            modelBuilder.Entity("Messenger.Domain.Chats.DirectChat", b =>
                {
                    b.HasOne("Messenger.Domain.Interlocutors.Member", "Member")
                        .WithOne()
                        .HasForeignKey("Messenger.Domain.Chats.DirectChat", "MemberId");
                });
#pragma warning restore 612, 618
        }
    }
}
